{% set name = "stardist-napari" %}
{% set version = "2022.12.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stardist-napari-{{ version }}.tar.gz
  sha256: 5755327d63a87c088c729e94588b99fc3fc81df55b133da0e9e7fd566362ce3d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - magicgui >=0.4.0
    - napari >=0.4.13
    - python >=3.7
    - stardist >=0.8.3
    - tensorflow

test:
  imports:
    - stardist_napari
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/stardist/stardist-napari
  summary: the napari plugin for StarDist, a deep learning based 2D and 3D object detection method with star-convex shapes.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - maweigert
    - uschmidt83
